# Generated by Django 4.2.2 on 2023-06-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_berries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Berries',
            new_name='Feeding',
        ),
    ]
