# Generated by Django 4.2.2 on 2023-06-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
